### ISSUE TITLE
How does it works?

### ISSUE THREAD

**Issue by ricky12502** [freehuntx/bomberpengu#4]
Hi! I was wondering how can i play this game, i press on the link and it redirects me to a blank page. I've also try to install the extension "Ruffle - Flash Emulator" but it didn't change the result. Thanks for your time!

**Comment by freehuntx** [comment]
I will take a look, maybe something broke.

**Comment by freehuntx** [comment]
Fixed. But multiplayer is not fully implemented yet. Currently you can just chat with others and play against a bot (To do freestyle)

**Comment by ricky12502** [comment]
Okay, thank you for your support and time, have a nice day!
